"use client";

import * as React from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { toast } from "sonner";
import { ArrowUpRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";
import { GenderBadge } from "@/components/ui/gender-badge";
import { LaneChip } from "@/components/ui/lane-chip";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { apiGet, apiPost } from "@/lib/api-client";
import { formatSecondsToTime } from "@/lib/scoring";
import { GAME_SCHOOL_LEVELS } from "@/lib/school-levels";
import { isHigherLevel } from "@/lib/utils";
import type { Level } from "@prisma/client";

interface QualifiedAthlete {
  participantId: string;
  firstName: string;
  lastName: string;
  gender: string;
  bibNumber: number;
  position: number;
  timeTaken: number | null;
  score: number | null;
  schoolName: string | null;
}

interface QualifiedGameGroup {
  gameId: string;
  gameName: string;
  gender: string;
  schoolLevel: string;
  isTimed: boolean;
  maxQualifiers: number;
  athletes: QualifiedAthlete[];
}

interface ChampionshipOption {
  id: string;
  name: string;
  level: Level;
}

const GENDER_FILTERS = [
  { value: "OVERALL", label: "All genders" },
  { value: "BOYS", label: "Boys" },
  { value: "GIRLS", label: "Girls" },
];
const SCHOOL_LEVEL_FILTERS = [{ value: "OVERALL", label: "All school levels" }, ...GAME_SCHOOL_LEVELS];

export function PromotionsPanel({ championshipId, currentLevel }: { championshipId: string; currentLevel: Level | undefined }) {
  const [gender, setGender] = React.useState("OVERALL");
  const [schoolLevel, setSchoolLevel] = React.useState("OVERALL");
  const [selected, setSelected] = React.useState<Set<string>>(new Set());
  const [targetChampionshipId, setTargetChampionshipId] = React.useState("");

  const { data, isLoading } = useQuery({
    queryKey: ["qualified-athletes", championshipId, gender, schoolLevel],
    queryFn: () =>
      apiGet<{ groups: QualifiedGameGroup[] }>(
        `/api/qualified-athletes?championshipId=${championshipId}&gender=${gender}&schoolLevel=${schoolLevel}`,
      ),
  });
  const groups = data?.groups ?? [];

  const { data: championshipsData } = useQuery({
    queryKey: ["championships-picker"],
    queryFn: () => apiGet<{ championships: ChampionshipOption[] }>("/api/championships"),
  });
  const higherLevelChampionships = (championshipsData?.championships ?? []).filter(
    (c) => currentLevel && isHigherLevel(c.level, currentLevel),
  );

  function toggle(id: string) {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  function toggleAllInGame(group: QualifiedGameGroup) {
    setSelected((prev) => {
      const next = new Set(prev);
      const allSelected = group.athletes.every((a) => next.has(a.participantId));
      for (const a of group.athletes) {
        if (allSelected) next.delete(a.participantId);
        else next.add(a.participantId);
      }
      return next;
    });
  }

  const promoteMutation = useMutation({
    mutationFn: () =>
      apiPost<{ promoted: Array<{ athlete: string; created: boolean; reason?: string }> }>("/api/participants/promote", {
        participantIds: Array.from(selected),
        targetChampionshipId,
      }),
    onSuccess: (result) => {
      const createdCount = result.promoted.filter((p) => p.created).length;
      const skipped = result.promoted.filter((p) => !p.created);
      toast.success(
        createdCount > 0
          ? `Promoted ${createdCount} athlete${createdCount === 1 ? "" : "s"}${skipped.length > 0 ? ` (${skipped.length} skipped)` : ""}`
          : "These athletes were already promoted to that championship",
      );
      setSelected(new Set());
    },
    onError: (error) => toast.error(error instanceof Error ? error.message : "Failed to promote athletes"),
  });

  return (
    <Card>
      <CardHeader className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <CardTitle>Qualified for Promotion</CardTitle>
          <CardDescription>
            Autogenerated from each Track &amp; Field event&apos;s Final only (never heats) - the top finishers up to
            that event&apos;s qualifier cap, ready to carry forward to a higher-level championship.
          </CardDescription>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <Select value={gender} onValueChange={setGender}>
            <SelectTrigger className="w-40"><SelectValue /></SelectTrigger>
            <SelectContent>
              {GENDER_FILTERS.map((g) => (
                <SelectItem key={g.value} value={g.value}>{g.label}</SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Select value={schoolLevel} onValueChange={setSchoolLevel}>
            <SelectTrigger className="w-48"><SelectValue /></SelectTrigger>
            <SelectContent>
              {SCHOOL_LEVEL_FILTERS.map((l) => (
                <SelectItem key={l.value} value={l.value}>{l.label}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="flex flex-wrap items-end gap-3 rounded-md border border-border p-4">
          <div className="w-64">
            <label className="text-sm font-medium text-foreground">Promote selected to</label>
            <Select value={targetChampionshipId} onValueChange={setTargetChampionshipId}>
              <SelectTrigger className="mt-1.5"><SelectValue placeholder="Select target championship" /></SelectTrigger>
              <SelectContent>
                {higherLevelChampionships.map((c) => (
                  <SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>
                ))}
              </SelectContent>
            </Select>
            {higherLevelChampionships.length === 0 && (
              <p className="mt-1.5 text-xs text-muted">No higher-level championship found that you manage.</p>
            )}
          </div>
          <Button
            disabled={selected.size === 0 || !targetChampionshipId || promoteMutation.isPending}
            onClick={() => promoteMutation.mutate()}
          >
            <ArrowUpRight className="h-4 w-4" />
            {promoteMutation.isPending ? "Promoting..." : `Promote ${selected.size} selected`}
          </Button>
        </div>

        {isLoading && <p className="text-muted">Loading qualified athletes...</p>}
        {!isLoading && groups.length === 0 && (
          <p className="text-muted">No Final results recorded yet for this filter - heats alone don&apos;t count.</p>
        )}
        {groups.map((group) => (
          <div key={group.gameId} className="space-y-2">
            <div className="flex items-center gap-2">
              <h3 className="font-medium text-foreground">{group.gameName}</h3>
              <GenderBadge gender={group.gender} />
              <span className="text-sm text-muted">
                Top {group.maxQualifiers} - {group.athletes.length} qualifier{group.athletes.length === 1 ? "" : "s"}
              </span>
              <Button size="sm" variant="ghost" className="ml-auto" onClick={() => toggleAllInGame(group)}>
                Select/deselect all
              </Button>
            </div>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead />
                  <TableHead>Pos</TableHead>
                  <TableHead>Bib</TableHead>
                  <TableHead>Athlete</TableHead>
                  <TableHead>Gender</TableHead>
                  <TableHead>Institution</TableHead>
                  <TableHead>{group.isTimed ? "Time" : "Score"}</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {group.athletes.map((a) => (
                  <TableRow key={a.participantId}>
                    <TableCell>
                      <input
                        type="checkbox"
                        checked={selected.has(a.participantId)}
                        onChange={() => toggle(a.participantId)}
                      />
                    </TableCell>
                    <TableCell><LaneChip value={a.position} rank={a.position} /></TableCell>
                    <TableCell><LaneChip value={a.bibNumber} /></TableCell>
                    <TableCell>{a.firstName} {a.lastName}</TableCell>
                    <TableCell><GenderBadge gender={a.gender} /></TableCell>
                    <TableCell>{a.schoolName ?? "-"}</TableCell>
                    <TableCell className="font-mono tabular-nums">
                      {group.isTimed ? (a.timeTaken !== null ? formatSecondsToTime(a.timeTaken) : "-") : (a.score ?? "-")}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        ))}
      </CardContent>
    </Card>
  );
}
