import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { withAudit } from "@/lib/audit";
import { ensureChampionshipSchool } from "@/lib/championship-schools";
import {
  requireChampionshipAccess,
  isGeographicallyRestricted,
  assertWithinGeographicScope,
  toErrorResponse,
} from "@/lib/authorize";
import { promoteAthletesSchema } from "@/lib/validations";
import { highestBib, nextSchoolBib } from "@/lib/learners";

export const dynamic = "force-dynamic";

/**
 * Carries specific qualifying Track & Field finalists (picked from the
 * autogenerated Final-only qualifiers list, see lib/qualified-athletes.ts)
 * into a higher-level championship's matching event - same category,
 * gender, school level, and event name, which must already exist there.
 * Mirrors /api/tournament-teams/promote's approach for ball games: never
 * auto-creates the target game, and is idempotent (re-running skips
 * athletes already promoted).
 */
export async function POST(request: Request) {
  try {
    const body: unknown = await request.json();
    const input = promoteAthletesSchema.parse(body);

    const targetChampionship = await prisma.championship.findUnique({ where: { id: input.targetChampionshipId } });
    if (!targetChampionship) return NextResponse.json({ error: "Target championship not found" }, { status: 404 });

    const promoted: Array<{ athlete: string; created: boolean; reason?: string }> = [];
    let nextBibNumber: number | null = null;

    for (const participantId of input.participantIds) {
      const origin = await prisma.participant.findUnique({
        where: { id: participantId },
        include: {
          game: { select: { championshipId: true, category: true, gender: true, schoolLevel: true, isTimed: true, name: true } },
          school: { select: { id: true, county: true, name: true } },
          heatParticipations: {
            where: { heat: { heatType: "final" } },
            select: { timeTaken: true },
            take: 1,
          },
        },
      });
      if (!origin) {
        promoted.push({ athlete: "Unknown athlete", created: false, reason: "not found" });
        continue;
      }
      const athleteName = `${origin.firstName} ${origin.lastName}`;

      const ctx = await requireChampionshipAccess(origin.game.championshipId, ["TOURNAMENT_ADMIN"]);
      await requireChampionshipAccess(input.targetChampionshipId, ["TOURNAMENT_ADMIN"]);

      if (origin.game.category !== "ATHLETICS") {
        promoted.push({ athlete: athleteName, created: false, reason: "not a Track & Field event" });
        continue;
      }

      const already = await prisma.participant.findFirst({
        where: { championshipId: input.targetChampionshipId, promotedFromParticipantId: origin.id },
      });
      if (already) {
        promoted.push({ athlete: athleteName, created: false, reason: "already promoted" });
        continue;
      }

      const targetGame = await prisma.game.findFirst({
        where: {
          championshipId: input.targetChampionshipId,
          category: "ATHLETICS",
          gender: origin.game.gender,
          schoolLevel: origin.game.schoolLevel,
          isTimed: origin.game.isTimed,
          name: { equals: origin.game.name, mode: "insensitive" },
        },
      });
      if (!targetGame) {
        promoted.push({
          athlete: athleteName,
          created: false,
          reason: `no matching "${origin.game.name}" event exists yet in the target championship`,
        });
        continue;
      }

      if (isGeographicallyRestricted(targetChampionship.level)) {
        assertWithinGeographicScope(targetChampionship.county, origin.school?.county);
      }

      // A school's learner keeps one learner record (and bib) at the next
      // level however many events they're promoted in - found by the learner
      // they came from, or by birth certificate entry number if the school
      // registered them there directly. Their photo, birth certificate number
      // and date of birth go with them.
      const originLearner = origin.learnerId
        ? await prisma.learner.findUnique({ where: { id: origin.learnerId } })
        : null;
      let targetLearner = originLearner
        ? await prisma.learner.findFirst({
            where: {
              championshipId: input.targetChampionshipId,
              OR: [
                { promotedFromLearnerId: originLearner.id },
                ...(originLearner.birthCertNumber ? [{ birthCertNumber: originLearner.birthCertNumber }] : []),
              ],
            },
          })
        : null;
      if (targetLearner) {
        const entered = await prisma.participant.findFirst({ where: { gameId: targetGame.id, learnerId: targetLearner.id }, select: { id: true } });
        if (entered) {
          promoted.push({ athlete: athleteName, created: false, reason: "already entered in that event" });
          continue;
        }
      }

      let bibNumber: number;
      if (targetLearner) {
        bibNumber = targetLearner.bibNumber;
      } else if (origin.schoolId && (await prisma.schoolBibRange.findUnique({
        where: { championshipId_schoolId: { championshipId: input.targetChampionshipId, schoolId: origin.schoolId } },
        select: { id: true },
      }))) {
        bibNumber = await nextSchoolBib(prisma, input.targetChampionshipId, origin.schoolId, origin.school?.name ?? "This school");
      } else {
        if (nextBibNumber === null) {
          nextBibNumber = (await highestBib(prisma, input.targetChampionshipId)) + 1;
        }
        bibNumber = nextBibNumber++;
      }

      // Seed the next level's personal best with this final's actual time,
      // so lane seeding at the next championship starts from real form
      // rather than nothing - preferring the Final heat's time if the event
      // used heats, falling back to the straight-final time on Participant.
      const personalBest = origin.heatParticipations[0]?.timeTaken ?? origin.timeTaken ?? null;

      const created = await withAudit({
        actorId: ctx.userId,
        operation: "INSERT",
        tableName: "participants",
        mutate: async (tx) => {
          // The athlete's school joins the next championship's school list
          // with them, so it's selectable there (bib ranges, participants).
          if (origin.schoolId) await ensureChampionshipSchool(input.targetChampionshipId, origin.schoolId, tx);
          if (originLearner && !targetLearner) {
            targetLearner = await tx.learner.create({
              data: {
                championshipId: input.targetChampionshipId,
                schoolId: originLearner.schoolId,
                firstName: originLearner.firstName,
                lastName: originLearner.lastName,
                gender: originLearner.gender,
                dateOfBirth: originLearner.dateOfBirth,
                birthCertNumber: originLearner.birthCertNumber,
                bibNumber,
                photo: originLearner.photo,
                photoUpdatedAt: originLearner.photoUpdatedAt,
                promotedFromLearnerId: originLearner.id,
              },
            });
          }
          return tx.participant.create({
            data: {
              championshipId: input.targetChampionshipId,
              gameId: targetGame.id,
              schoolId: origin.schoolId,
              tournamentTeamId: origin.tournamentTeamId,
              firstName: origin.firstName,
              lastName: origin.lastName,
              gender: origin.gender,
              dateOfBirth: origin.dateOfBirth,
              bibNumber,
              personalBest,
              promotedFromParticipantId: origin.id,
              learnerId: targetLearner?.id ?? null,
            },
          });
        },
        recordId: (result) => result.id,
        newData: { promotedFromParticipantId: origin.id, targetChampionshipId: input.targetChampionshipId },
      });

      promoted.push({ athlete: `${created.firstName} ${created.lastName}`, created: true });
    }

    return NextResponse.json({ promoted });
  } catch (error) {
    const { body, status } = toErrorResponse(error);
    return NextResponse.json(body, { status });
  }
}
