import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { withAudit } from "@/lib/audit";
import {
  requireChampionshipAccess,
  isGeographicallyRestricted,
  assertWithinGeographicScope,
  toErrorResponse,
} from "@/lib/authorize";
import { promoteAthletesSchema } from "@/lib/validations";
import { assignNextBibNumber } from "@/lib/scoring";

export const dynamic = "force-dynamic";

/**
 * Carries specific qualifying Track & Field finalists (picked from the
 * autogenerated Final-only qualifiers list, see lib/qualified-athletes.ts)
 * into a higher-level championship's matching event - same category,
 * gender, school level, and event name, which must already exist there.
 * Mirrors /api/tournament-teams/promote's approach for ball games: never
 * auto-creates the target game, and is idempotent (re-running skips
 * athletes already promoted).
 */
export async function POST(request: Request) {
  try {
    const body: unknown = await request.json();
    const input = promoteAthletesSchema.parse(body);

    const targetChampionship = await prisma.championship.findUnique({ where: { id: input.targetChampionshipId } });
    if (!targetChampionship) return NextResponse.json({ error: "Target championship not found" }, { status: 404 });

    const promoted: Array<{ athlete: string; created: boolean; reason?: string }> = [];
    let nextBibNumber: number | null = null;

    for (const participantId of input.participantIds) {
      const origin = await prisma.participant.findUnique({
        where: { id: participantId },
        include: {
          game: { select: { championshipId: true, category: true, gender: true, schoolLevel: true, isTimed: true, name: true } },
          school: { select: { id: true, county: true, name: true } },
          heatParticipations: {
            where: { heat: { heatType: "final" } },
            select: { timeTaken: true },
            take: 1,
          },
        },
      });
      if (!origin) {
        promoted.push({ athlete: "Unknown athlete", created: false, reason: "not found" });
        continue;
      }
      const athleteName = `${origin.firstName} ${origin.lastName}`;

      const ctx = await requireChampionshipAccess(origin.game.championshipId, ["TOURNAMENT_ADMIN"]);
      await requireChampionshipAccess(input.targetChampionshipId, ["TOURNAMENT_ADMIN"]);

      if (origin.game.category !== "ATHLETICS") {
        promoted.push({ athlete: athleteName, created: false, reason: "not a Track & Field event" });
        continue;
      }

      const already = await prisma.participant.findFirst({
        where: { championshipId: input.targetChampionshipId, promotedFromParticipantId: origin.id },
      });
      if (already) {
        promoted.push({ athlete: athleteName, created: false, reason: "already promoted" });
        continue;
      }

      const targetGame = await prisma.game.findFirst({
        where: {
          championshipId: input.targetChampionshipId,
          category: "ATHLETICS",
          gender: origin.game.gender,
          schoolLevel: origin.game.schoolLevel,
          isTimed: origin.game.isTimed,
          name: { equals: origin.game.name, mode: "insensitive" },
        },
      });
      if (!targetGame) {
        promoted.push({
          athlete: athleteName,
          created: false,
          reason: `no matching "${origin.game.name}" event exists yet in the target championship`,
        });
        continue;
      }

      if (isGeographicallyRestricted(targetChampionship.level)) {
        assertWithinGeographicScope(targetChampionship.county, origin.school?.county);
      }

      let bibNumber: number;
      if (origin.schoolId) {
        const range = await prisma.schoolBibRange.findUnique({
          where: { championshipId_schoolId: { championshipId: input.targetChampionshipId, schoolId: origin.schoolId } },
        });
        if (range) {
          const existing = await prisma.participant.findMany({
            where: { championshipId: input.targetChampionshipId, schoolId: origin.schoolId },
            select: { bibNumber: true },
          });
          bibNumber = assignNextBibNumber(
            origin.schoolId,
            { schoolId: range.schoolId, rangeStart: range.rangeStart, rangeEnd: range.rangeEnd },
            existing.map((p) => p.bibNumber),
          );
        } else {
          if (nextBibNumber === null) {
            const highest = await prisma.participant.findFirst({
              where: { championshipId: input.targetChampionshipId },
              orderBy: { bibNumber: "desc" },
              select: { bibNumber: true },
            });
            nextBibNumber = (highest?.bibNumber ?? 0) + 1;
          }
          bibNumber = nextBibNumber++;
        }
      } else {
        if (nextBibNumber === null) {
          const highest = await prisma.participant.findFirst({
            where: { championshipId: input.targetChampionshipId },
            orderBy: { bibNumber: "desc" },
            select: { bibNumber: true },
          });
          nextBibNumber = (highest?.bibNumber ?? 0) + 1;
        }
        bibNumber = nextBibNumber++;
      }

      // Seed the next level's personal best with this final's actual time,
      // so lane seeding at the next championship starts from real form
      // rather than nothing - preferring the Final heat's time if the event
      // used heats, falling back to the straight-final time on Participant.
      const personalBest = origin.heatParticipations[0]?.timeTaken ?? origin.timeTaken ?? null;

      const created = await withAudit({
        actorId: ctx.userId,
        operation: "INSERT",
        tableName: "participants",
        mutate: (tx) =>
          tx.participant.create({
            data: {
              championshipId: input.targetChampionshipId,
              gameId: targetGame.id,
              schoolId: origin.schoolId,
              tournamentTeamId: origin.tournamentTeamId,
              firstName: origin.firstName,
              lastName: origin.lastName,
              gender: origin.gender,
              bibNumber,
              personalBest,
              promotedFromParticipantId: origin.id,
            },
          }),
        recordId: (result) => result.id,
        newData: { promotedFromParticipantId: origin.id, targetChampionshipId: input.targetChampionshipId },
      });

      promoted.push({ athlete: `${created.firstName} ${created.lastName}`, created: true });
    }

    return NextResponse.json({ promoted });
  } catch (error) {
    const { body, status } = toErrorResponse(error);
    return NextResponse.json(body, { status });
  }
}
