import { prisma } from "./prisma";

export interface QualifiedAthlete {
  participantId: string;
  firstName: string;
  lastName: string;
  gender: string;
  bibNumber: number;
  position: number;
  timeTaken: number | null;
  score: number | null;
  schoolName: string | null;
}

export interface QualifiedGameGroup {
  gameId: string;
  gameName: string;
  gender: string;
  schoolLevel: string;
  isTimed: boolean;
  maxQualifiers: number;
  athletes: QualifiedAthlete[];
}

/**
 * The autogenerated "who qualifies to promote" list for Track & Field
 * (Athletics) events: top `maxQualifiers` finishers, taken from each game's
 * FINAL only - never from heats, which are just a preliminary cut. Most
 * events (heats-based sprints) score their Final as a Heat row
 * (heatType "final"); events run straight to a final with no heats at all
 * (e.g. long-distance races) score directly on Participant instead, so both
 * sources are checked per game.
 */
export async function computeQualifiedAthletes(
  championshipId: string,
  filters: { gender?: string; schoolLevel?: string } = {},
): Promise<QualifiedGameGroup[]> {
  const games = await prisma.game.findMany({
    where: {
      championshipId,
      category: "ATHLETICS",
      ...(filters.gender && filters.gender !== "OVERALL" ? { gender: filters.gender as "BOYS" | "GIRLS" | "MIXED" } : {}),
      ...(filters.schoolLevel && filters.schoolLevel !== "OVERALL"
        ? { schoolLevel: filters.schoolLevel as "PRIMARY" | "JS" | "SENIOR_SCHOOL" | "TERTIARY" }
        : {}),
    },
    include: {
      heats: {
        where: { heatType: "final" },
        include: {
          participants: {
            where: { position: { not: null } },
            orderBy: { position: "asc" },
            include: {
              participant: {
                select: {
                  id: true,
                  firstName: true,
                  lastName: true,
                  gender: true,
                  bibNumber: true,
                  school: { select: { name: true } },
                  tournamentTeam: { select: { name: true } },
                },
              },
            },
          },
        },
      },
      participants: {
        where: { position: { not: null } },
        orderBy: { position: "asc" },
        select: {
          id: true,
          firstName: true,
          lastName: true,
          gender: true,
          bibNumber: true,
          position: true,
          timeTaken: true,
          score: true,
          school: { select: { name: true } },
          tournamentTeam: { select: { name: true } },
        },
      },
    },
    orderBy: { name: "asc" },
  });

  const groups: QualifiedGameGroup[] = [];
  for (const game of games) {
    const finalHeat = game.heats[0];
    const athletes: QualifiedAthlete[] = finalHeat
      ? finalHeat.participants.slice(0, game.maxQualifiers).map((hp) => ({
          participantId: hp.participant.id,
          firstName: hp.participant.firstName,
          lastName: hp.participant.lastName,
          gender: hp.participant.gender,
          bibNumber: hp.participant.bibNumber,
          position: hp.position as number,
          timeTaken: hp.timeTaken ? Number(hp.timeTaken) : null,
          score: hp.score ? Number(hp.score) : null,
          schoolName: hp.participant.school?.name ?? hp.participant.tournamentTeam?.name ?? null,
        }))
      : game.participants.slice(0, game.maxQualifiers).map((p) => ({
          participantId: p.id,
          firstName: p.firstName,
          lastName: p.lastName,
          gender: p.gender,
          bibNumber: p.bibNumber,
          position: p.position as number,
          timeTaken: p.timeTaken ? Number(p.timeTaken) : null,
          score: p.score ? Number(p.score) : null,
          schoolName: p.school?.name ?? p.tournamentTeam?.name ?? null,
        }));

    if (athletes.length === 0) continue;
    groups.push({
      gameId: game.id,
      gameName: game.name,
      gender: game.gender,
      schoolLevel: game.schoolLevel,
      isTimed: game.isTimed,
      maxQualifiers: game.maxQualifiers,
      athletes,
    });
  }
  return groups;
}
