-- AlterEnum
ALTER TYPE "Role" ADD VALUE 'GAME_COORDINATOR';
ALTER TYPE "Role" ADD VALUE 'CHIEF_CALLROOM_MANAGER';
ALTER TYPE "Role" ADD VALUE 'CHIEF_TRACK_JUDGE';
ALTER TYPE "Role" ADD VALUE 'CHIEF_FIELD_JUDGE';
ALTER TYPE "Role" ADD VALUE 'CHIEF_RECORDER';
